jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: "database"
      schema: "main"
      schemas_and_paths:
        main: "jaffle_shop.db"
      schema_directory: "jaffle_shop.db"
    # dev:
    # type: duckdb
    # path: 'jaffle_shop.duckdb'
    # threads: 24
